# Generated by Django 4.1.4 on 2023-02-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
